swagger: "2.0"
info:
  title: Transactions API
  version: 1.0.0
host: localhost:3001
basePath: /api/v1
schemes:
  - http
tags:
  - name: Transaction
    description: User transactions
paths:
  /transactions:
    get:
      tags:
        - Transaction
      summary: Retrieve all transactions for the current month
      parameters:
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transactions (use the current month for most recent transactions format MM)
          default: current month
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
      responses:
        200:
          description: List of transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transactions"
        400:
          description: Invalid request
        401:
          description: Unauthorized - User not authenticated
        500:
          description: Internal server error
          
    post:
      tags:
        - Transaction
      summary: Add a new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Transaction"
          required: true
      responses:
        200:
          description: Transaction successfully created
        400:
          description: Invalid request (incorrect transaction data)
        401:
          description: Unauthorized - User not authenticated
        500:
          description: Internal server error

  /transactions/{id}:
    parameters:
      - in: path
        name: id
        type: string
        required: true
        description: Transaction identifier

    get:
      tags:
        - Transaction
      summary: Retrieve a specific transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
      responses:
        200:
          description: Transaction
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized - User not authenticated
        403:
          description: Forbidden - User doesn't have permission to perform this action
        404:
          description: Transaction not found
        500:
          description: Internal server error

    patch:
      tags:
        - Transaction
      summary: Modify an existing transaction (selectively)
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/PatchTransaction"
          required: true
      responses:
        200:
          description: Transaction successfully updated
        400:
          description: Invalid request (incorrect transaction data)
        401:
          description: Unauthorized - User not authenticated
        403:
          description: Forbidden - User doesn't have permission to perform this action
        404:
          description: Transaction not found
        500:
          description: Internal server error

    delete:
      tags:
        - Transaction
      summary: Delete a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
      responses:
        200:
          description: Transaction information deleted successfully
        401:
          description: Unauthorized - User not authenticated
        403:
          description: Forbidden - User doesn't have permission to perform this action
        404:
          description: Transaction not found
        500:
          description: Internal server error

definitions:
  Transactions:
    type: object
    properties:
      accountType:
        type: string
        description: Type du compte
      balanceTotal:
        type: number
        format: float
        description: Solde du compte après la transaction
        
  Transaction:
    type: object
    properties:
      id:
        type: number
        description: Identifiant de la transaction
      accountType:
        type: string
        description: Type du compte
      amount:
        type: number
        format: float
        description: Montant de la transaction
      balance:
        type: number
        format: float
        description: Solde du compte après la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      transactionType:
        type: string
        description: Type de la transaction
      category:
        type: string
        description: Catégorie de la transaction
      notes:
        type: string
        description: Notes de la transaction
    required:
      - accountType
      - date
      - amount
      - transactionType

  PatchTransaction:
    type: object
    properties:
      category:
        type: string
        description: The category of the transaction to be updated (optional)
      notes:
        type: string
        description: Notes of transaction to be updated (optional)
    additionalProperties: false